In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df1=pd.read_csv('../data_cleaned/clean.csv')
# df2=pd.read_csv('../data_cleaned/clean.txt')

In [ ]:
df1.head()

,source_file,text
0,/linux-data/projects/ioe_purwanchal_campus_iic...,यसरी व्यवस्थापन गर्दैछ बिपी कोइराला क्यान्सर अ...
1,/linux-data/projects/ioe_purwanchal_campus_iic...,प्रत्यारोपणमा उपयोग हुने वस्तु सरकारी फार्मेसी...
2,/linux-data/projects/ioe_purwanchal_campus_iic...,मेचीनगरमा ‘अफ्रिकन स्वाइन फ्लू’ र ‘लम्पी स्किन...
3,/linux-data/projects/ioe_purwanchal_campus_iic...,अलपत्र भएका आधारभूत अस्पताल साउनबाटै सञ्चालनमा...
4,/linux-data/projects/ioe_purwanchal_campus_iic...,कालीमाटीमा भित्रिएका १७४ प्रकारका तरकारीमा विषादी

In [ ]:
df1.drop("source_file",axis=1,inplace=True)

In [ ]:
df1.head()

                                                text
0  यसरी व्यवस्थापन गर्दैछ बिपी कोइराला क्यान्सर अ...
1  प्रत्यारोपणमा उपयोग हुने वस्तु सरकारी फार्मेसी...
2  मेचीनगरमा ‘अफ्रिकन स्वाइन फ्लू’ र ‘लम्पी स्किन...
3  अलपत्र भएका आधारभूत अस्पताल साउनबाटै सञ्चालनमा...
4  कालीमाटीमा भित्रिएका १७४ प्रकारका तरकारीमा विषादी

In [ ]:
combined = pd.concat([df1, df2], axis=0)

In [ ]:
combined.shape

(1488300, 2)

In [ ]:
combined.head()

                                                text source_file
0  यसरी व्यवस्थापन गर्दैछ बिपी कोइराला क्यान्सर अ...         NaN
1  प्रत्यारोपणमा उपयोग हुने वस्तु सरकारी फार्मेसी...         NaN
2  मेचीनगरमा ‘अफ्रिकन स्वाइन फ्लू’ र ‘लम्पी स्किन...         NaN
3  अलपत्र भएका आधारभूत अस्पताल साउनबाटै सञ्चालनमा...         NaN
4  कालीमाटीमा भित्रिएका १७४ प्रकारका तरकारीमा विषादी         NaN

In [ ]:
combined.drop("source_file",axis=1,inplace=True)

In [ ]:
combined.head()

                                                text
0  यसरी व्यवस्थापन गर्दैछ बिपी कोइराला क्यान्सर अ...
1  प्रत्यारोपणमा उपयोग हुने वस्तु सरकारी फार्मेसी...
2  मेचीनगरमा ‘अफ्रिकन स्वाइन फ्लू’ र ‘लम्पी स्किन...
3  अलपत्र भएका आधारभूत अस्पताल साउनबाटै सञ्चालनमा...
4  कालीमाटीमा भित्रिएका १७४ प्रकारका तरकारीमा विषादी

In [ ]:
combined.to_csv("combined.csv", index=False)